language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq hhvm
script:
  - for i in $(find ./scripts/ -name *.php -type f); do echo $i; done;
